Repository czbiohub-sf/iohub, pull requests merged in 2023-08, with the labels that each got.

#166 Add position labels to ndtiff metadata
  .gitignore
  iohub/multipagetiff.py
  iohub/ndtiff.py
  iohub/reader_base.py
  setup.cfg
  tests/conftest.py
  tests/reader/test_pycromanager.py
Labels: enhancement, μManager

#173 Print scale in `iohub info`
  iohub/reader.py
  tests/cli/test_cli.py
  tests/conftest.py
Labels: enhancement

#175 Only set array transformation upon creation of FOVs
  iohub/ngff.py
  tests/test_converter.py
Labels: bug, NGFF

#179 Support MM 2.0.1 for single page TIFFs
  iohub/singlepagetiff.py
Labels: μManager, maintenance

#178 Enable XYZ chunking at conversion
  iohub/cli/cli.py
  iohub/convert.py
  iohub/ndtiff.py
  tests/cli/test_cli.py
Labels: enhancement, μManager
