Repository czbiohub-sf/iohub, pull requests merged in 2023-04, with the labels that each got.

#97 Initialize Zarr arrays in TIFF readers as zero-filled
  iohub/convert.py
  iohub/multipagetiff.py
  iohub/upti.py
Labels: bug, μManager

#100 Suppress CLI warning for NGFF v0.1 datasets
  iohub/reader.py
Labels: bug, NGFF

#107 Preparing for dev pre-release on PyPI
  .github/workflows/test.yml
  README.md
  docs/source/api/mm_converter.rst
  docs/source/api/mm_ometiff_reader.rst
  docs/source/api/mm_reader.rst
  docs/source/api/mm_sequence_reader.rst
  docs/source/api/ndtiff.rst
  docs/source/api/ngff.rst
  docs/source/api/pycromanager.rst
  docs/source/api/upti.rst
  docs/source/contact_us/github.rst
  docs/source/index.rst
  iohub/ngff.py
  iohub/reader_base.py
  setup.cfg
Labels: documentation, maintenance, CI

#110 Fix python version requirement
  setup.cfg
Labels: bug

#114 Add Clear Control dataset support
  docs/source/api/clearcontrol.rst
  docs/source/index.rst
  examples/view_clearcontrol_dataset.py
  iohub/clearcontrol.py
  iohub/ngff.py
  setup.cfg
  tests/clearcontrol/test_clearcontrol.py
Labels: enhancement

#109 adding a coordinate transformation example.
  examples/coordinate_transform.py
Labels: documentation, enhancement

#116 Fix Windows CLI tests
  iohub/cli/cli.py
  tests/cli/test_cli.py
Labels: bug, CI
