Repository czbiohub-sf/iohub, pull requests merged in 2023-02, with the labels that each got.

#51 Add zarr to install_requires
  setup.cfg
Labels: bug, maintenance

#46 Rename `WaveorderReader` to `ImageReader`
  iohub/cli/cli.py
  iohub/pycromanager.py
  iohub/reader.py
  iohub/zarrfile.py
  tests/reader/test_reader.py
  tests/reader/test_zarrfile.py
Labels: enhancement

#54 Fix example in README
  README.md
Labels: bug, documentation

#63 Infer Zarr dimension separator from NGFF version
  iohub/reader.py
  iohub/zarrfile.py
Labels: bug, NGFF

#61 Add shorthand to get raw data in NGFF positions
  iohub/ngff.py
  tests/ngff/test_ngff.py
Labels: enhancement, NGFF

#58 Methods for modifying channels in NGFF positions
  examples/single_fov_ome_zarr.py
  iohub/ngff.py
  tests/ngff/test_ngff.py
Labels: enhancement, NGFF

#70 Get NGFF channel index from name
  examples/single_fov_ome_zarr.py
  iohub/ngff.py
  tests/ngff/test_ngff.py
Labels: enhancement, NGFF

#67 Count valid TIFF pages when gathering index map
  iohub/multipagetiff.py
  setup.cfg
Labels: bug
