Repository czbiohub-sf/iohub, pull requests merged in 2023-07, with the labels that each got.

#154 Improve CC gallery example
  docs/examples/view_clearcontrol_dataset.py
  docs/source/conf.py
Labels: documentation, enhancement

#143 Gather FOVs into plates
  iohub/ngff.py
  tests/ngff/test_ngff.py
Labels: enhancement, NGFF

#153 Examples gallery
  .github/workflows/pr.yml
  .gitignore
  CONTRIBUTING.md
  docs/Makefile
  docs/examples/README.rst
  docs/examples/run_coordinate_transform.py
  docs/examples/run_large_array_ome_zarr.py
  docs/examples/run_multi_fov_hcs_ome_zarr.py
  docs/examples/run_single_fov_ome_zarr.py
  docs/examples/run_tiled_ome_zarr.py
  docs/examples/run_view_clearcontrol_dataset.py
  docs/source/conf.py
  docs/source/index.rst
  examples/large_array_ome_zarr.py
  examples/view_clearcontrol_dataset.py
  setup.cfg
Labels: documentation, enhancement, CI

#165 Pin zarr version to avoid tifffile issue
  setup.cfg
Labels: bug, maintenance, upstream
