Repository czbiohub-sf/iohub, pull requests merged in 2023-03, with the labels that each got.

#72 Update package metadata
  setup.cfg
Labels: meta, maintenance

#79 Specify minimum zarr-python version
  setup.cfg
Labels: bug, maintenance

#28 Docs
  .github/workflows/docs.yml
  CONTRIBUTING.md
  docs/Makefile
  docs/source/api/mm_ometiff_reader.rst
  docs/source/api/mm_sequence_reader.rst
  docs/source/api/ngff.rst
  docs/source/api/pycromanager.rst
  docs/source/api/upti.rst
  docs/source/conf.py
  docs/source/contact_us/github.rst
  docs/source/getting_started/install.rst
  docs/source/getting_started/why.rst
  docs/source/index.rst
  iohub/ngff.py
  setup.cfg
Labels: documentation

#80 Update docs.yml
  .github/workflows/docs.yml
Labels: bug, documentation

#81 Update docs.yml
  .github/workflows/docs.yml
Labels: bug, documentation

#71 Image reading entry point
  iohub/cli/cli.py
  iohub/multipagetiff.py
  iohub/ndtiff.py
  iohub/reader.py
  iohub/reader_base.py
  iohub/singlepagetiff.py
  iohub/upti.py
  iohub/zarrfile.py
  tests/__init__.py
  tests/reader/test_pycromanager.py
  tests/reader/test_reader.py
  tests/reader/test_zarrfile.py
Labels: enhancement

#73 Convenient tiled array I/O with NGFF
  examples/tiled_ome_zarr.py
  iohub/ngff.py
  tests/ngff/test_ngff.py
Labels: enhancement

#76 Micro-Manager TIFF formats Converter
  iohub/cli/cli.py
  iohub/convert.py
  iohub/singlepagetiff.py
  setup.cfg
  tests/cli/__init__.py
  tests/cli/test_cli.py
  tests/test_converter.py
Labels: enhancement, NGFF, μManager

#87 NGFF method to create zero-filled lazy images
  examples/large_array_ome_zarr.py
  iohub/ngff.py
  tests/ngff/test_ngff.py
Labels: bug, enhancement, NGFF

#95 Avoid the `tifffile` version with breaking changes
  setup.cfg
Labels: bug, maintenance, CI

#96 Skip empty image instead of failing in conversion
  iohub/convert.py
Labels: bug, μManager

#92 Improve CLI and API reading entry points
  README.md
  iohub/__init__.py
  iohub/cli/cli.py
  iohub/convert.py
  iohub/reader.py
  tests/__init__.py
  tests/cli/test_cli.py
  tests/reader/test_reader.py
  tests/reader/test_zarrfile.py
  tests/test_converter.py
Labels: bug, enhancement

#91 Allow different tile data types for NGFF
  iohub/ngff.py
  tests/ngff/test_ngff.py
Labels: bug, NGFF

#102 Use fixed separator `/` to join row_name and col_name
  iohub/ngff.py
Labels: bug, NGFF

#101 Adding automatic channel name to Hex color mapping
  iohub/display_utils.py
  iohub/ngff.py
  iohub/ngff_meta.py
  setup.cfg
  tests/test_display_utils.py
Labels: enhancement, good first issue
