Repository czbiohub-sf/iohub, pull requests merged in 2025-07, with the labels that each got.

#242 adding conversion to tensorstore
  iohub/ngff/nodes.py
  setup.cfg
  tests/ngff/test_ngff.py
Labels: enhancement

#313 Fix docs build for new versions
  docs/poly.py
  docs/source/_static/switcher.json
  docs/source/api/ngff.rst
Labels: bug, documentation, CI

#315 More robust conversion
  iohub/ndtiff.py
Labels: μManager
