Repository czbiohub-sf/iohub, pull requests merged in 2025-05, with the labels that each got.

#298 Catch json decoding error from incomplete NDTIFF
  iohub/ndtiff.py
Labels: μManager

#288 Update packaging metadata for 0.2.0
  CITATION.cff
  README.md
  docs/source/_static/switcher.json
  iohub/reader.py
  tests/cli/test_cli.py
Labels: documentation, maintenance, CI

#302 Catch truncated unicode error in NDTIFF
  iohub/ndtiff.py
Labels: enhancement, μManager

#299 Add logo
  docs/source/_static/iohub.svg
Labels: documentation, enhancement

#303 Pin tifffile for zarr-python 2 compatibility
  setup.cfg
Labels: maintenance

#306 Convert micro-manager acquired line acquisitions
  iohub/mm_fov.py
Labels: enhancement, μManager
